---
- name: Install OS dependencies - Debian Buster
  apt:  
    pkg: [
      's4cmd',
      'xz-utils'
    ]
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - backup
    - deps

- name: Install OS dependencies
  apt:  
    pkg: [
      'xz-utils'
    ]
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8" or ansible_distribution == "Ubuntu"
  tags:
    - backup
    - deps

- name: Create dedicated user
  user: name=kernelci
        state=present
        system=yes
        home=/home/kernelci
  tags:
    - backup

- name: Copy backup script
  template: src=mongodb-backup.sh
        dest=/home/kernelci/mongodb-backup.sh
        owner=kernelci
        group=nogroup
        mode=0554
  tags:
    - backup

- name: Set up cronjob for backup
  cron: name="Backup Kernel CI MongoDB"
        user=kernelci
        state=present
        job="/home/kernelci/mongodb-backup.sh"
        cron_file=kernelci-backup
        weekday=1-6
        hour=4
        minute=5
  tags:
    - backup
    - cron
